### ISSUE TITLE
Thx!!

### ISSUE THREAD

**Issue by Dextura** [Snakelegendary/BO2-plutonium-gsc-guide#1]
Thanks so much for the guide on learning how to code in gsc means alot, now i can program with me friends mystic codes and a few others that know gsc

**Comment by Dextura** [comment]
but perhaps we could collab idk

**Comment by AkbarHashimi** [comment]
im learning too, so as I learn things i try to explain it in this wiki for others. I know black ops 2 plutonium modding is confusing, so having one resource should help others. Any collaboration is welcome :)

**Comment by AkbarHashimi** [comment]
i sent you a discord friend request mine is LUV IS RAGE#6884
